### ISSUE TITLE
Code is useless

### ISSUE THREAD

**Issue by Zdendaki** [davcs86/csharp-uhwid#2]
I've downloaded your app and the source code is useless (redudant '+', variables refer on bad classes, etc.)

**Comment by iskrzycki** [comment]
Yeah, I had the same problem, but finally it's working for me. Solution is quite simple:
- manually add reference to System.Management in your project
- remove '+' marks in UHWID.cs file
- rename classes and methods in UHWID.cs, e.g. `DiskId.GetDiskId();` should be `DiskID.getDiskID();`

**Comment by l4km47** [comment]
i haven't these issues

**Comment by iskrzycki** [comment]
Look there: https://github.com/davcs86/csharp-uhwid/blob/master/UHWID/UHWID.cs and tell me, that those '+' at the beginning of the lines are valid C# code :)

**Comment by davcs86** [comment]
Fixed [https://github.com/davcs86/csharp-uhwid/commit/d93c25ea5785ebecb917acc33580a3ea5dea0755?diff=split](https://github.com/davcs86/csharp-uhwid/commit/d93c25ea5785ebecb917acc33580a3ea5dea0755?diff=split).

**Comment by davcs86** [comment]
I'm going to close this issue. @Zdendaki, @iskrzycki if you have more comments/suggestions, please let me know in a new issue.
